- name: Configure Backstage
  hosts: localhost

  vars:
    users_csv_file: https://raw.githubusercontent.com/rh-trucathon/user_management/main/userFiles/superheroes-p3.csv

  tasks:

  - name: Ensure the user exists
    ansible.builtin.template:
      src: user.j2
      dest: '{{ playbook_dir }}/user.yaml'
    vars:
     csvFile: "{{ lookup('ansible.builtin.url', users_csv_file, wantlist=True)[1:] }}"

